default_language_version:
    python: python3.12
repos:
  # Python hooks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        args: ["--args=--config=__GIT_WORKING_DIR__/.tflint.hcl"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
        args:
          - --allow-multiple-documents
          - --unsafe
        exclude: ^applications
      - id: detect-private-key
      - id: trailing-whitespace
        exclude_types:
          - markdown
      - id: end-of-file-fixer
      - id: check-added-large-files
