default_language_version:
    python: python3.12
repos:
  # Python hooks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy src
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
        args:
          - --allow-multiple-documents
          - --unsafe
        exclude: ^applications
      - id: detect-private-key
      - id: trailing-whitespace
        exclude_types:
          - markdown
      - id: end-of-file-fixer
      - id: check-added-large-files
