# Required: project key from ATC Do-It-Yourself portal
sonar.projectKey=4wheels-m_clusters-4wm

# Python version
sonar.python.version=3.9

# Path is relative to the sonar-project.properties file.
sonar.sources=src/

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Project specific config
sonar.python.coverage.reportPaths=coverage.xml
sonar.host.url=https://sonar.atc-github.azure.cloud.bmw/instance11
