environment: int

image:
  repository: 845910084933.dkr.ecr.eu-central-1.amazonaws.com/clusters-4wm
  tag: <IMAGE_TAG>

ingress:
  enabled: true
  certManagerEnabled: true
  hosts:
    - host: clusters-4wm-test.apps.<CLUSTER_DNS>
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: tls
      hosts:
        - clusters-4wm-test.apps.<CLUSTER_DNS>

replicas: 1

autoscaling:
  enabled: false

database:
  external: false
