name: CI Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ci-checks-${{ github.ref }}
  cancel-in-progress: false

jobs:
  pre-commit:
    name: Pre-commit checks
    uses: 4WHEELS-M/workflows/.github/workflows/pre-commit.yaml@0.20.0
    with:
      branch-name: ${{ github.event.pull_request.head.ref }}

  tests:
    name: Tests
    needs: pre-commit
    uses: 4WHEELS-M/workflows/.github/workflows/python-tests.yaml@0.20.0
    secrets: inherit
    with:
      branch-name: ${{ github.event.pull_request.head.ref }}
      pr-number: ${{ github.event.pull_request.number }}

  static-code-analysis:
    name: Static code analysis
    needs: tests
    uses: 4WHEELS-M/workflows/.github/workflows/sonarqube.yaml@0.20.0
    with:
      branch-name: ${{ github.event.pull_request.head.ref }}
      coverage-report-artifact: coverage-report-artifact
      enforce-quality-gate: true
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
