name: Request reviews

on:
  pull_request:
    branches: [ main ]

jobs:
  request-reviews:
    uses: 4WHEELS-TF/workflows/.github/workflows/request-reviews.yaml@main
    with:
      pr_number: ${{ github.event.number }}
      pr_owner: ${{ github.event.pull_request.user.login }}
    secrets:
      app_private_key: ${{ secrets.REVIEW_REQUEST_PRIVATE_KEY }}
