apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clusters-4wm.fullname" . }}-api
  labels:
    {{- include "clusters-4wm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "clusters-4wm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "clusters-4wm.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ toYaml .Values.api.command | nindent 10 }}
          envFrom:
            {{- range $vault_secret := .Values.api.vault_credentials }}
            - secretRef:
                name: {{ include "clusters-4wm.fullname" $ }}-{{ $vault_secret.secretName }}
            {{- end }}
          env:
            - name: APP_VERSION
              value:  {{ .Values.image.tag | default .Chart.AppVersion }}
            - name: APP_ENVIRONMENT
              value: {{ .Values.environment }}
            - name: DB_HOST
              value: {{ include "clusters-4wm.databaseHost" . }}
            - name: DB_NAME
              value: {{ .Values.database.name }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ include "clusters-4wm.fullname" . }}-db-credentials
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ include "clusters-4wm.fullname" . }}-db-credentials
            - name: ADGR_GROUP_REGEX
              value: {{ .Values.namespaces.adgr_group_regex }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 60
          startupProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 10
            periodSeconds: 10
          #readinessProbe:
          #  httpGet:
          #    path: /ready
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
