{{ range $vault_credentials := .Values.api.vault_credentials }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "clusters-4wm.fullname" $ }}-{{ $vault_credentials.secretName }}
spec:
  refreshInterval: 10m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ include "clusters-4wm.fullname" $ }}-{{ $vault_credentials.secretName }}
  data:
  {{- range .properties }}
  - secretKey: {{ .secretKey }}
    remoteRef:
      key: {{ tpl $vault_credentials.path $ }}
      property: {{ .property }}
  {{- end -}}
{{- end -}}
