"""Add constraint to repository field

Revision ID: 16b351bb42a8
Revises: 305ae638786e
Create Date: 2022-08-26 09:30:38.166076

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "16b351bb42a8"
down_revision = "305ae638786e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "cluster", ["repository"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "cluster", type_="unique")
    # ### end Alembic commands ###
