"""init

Revision ID: 305ae638786e
Revises:
Create Date: 2022-08-05 16:00:47.461393

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "305ae638786e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cluster",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subscription", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("release", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("environment", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("internal", sa.Boolean(), nullable=False),
        sa.Column("repository", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("node_min_count", sa.Integer(), nullable=False),
        sa.Column("node_max_count", sa.Integer(), nullable=False),
        sa.Column("provider_region", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tshirt_size", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("infra_revision", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kubernetes_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "operation",
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("jenkins_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("cluster_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["cluster.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("operation")
    op.drop_table("cluster")
    # ### end Alembic commands ###
