"""Add operations fields

Revision ID: 4bf4403793c7
Revises: 16b351bb42a8
Create Date: 2022-08-31 08:27:58.443599

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "4bf4403793c7"
down_revision = "16b351bb42a8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "operation",
        sa.Column("cluster_repository", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.alter_column("operation", "cluster_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "cluster",
        "id",
        existing_type=sa.INTEGER(),
        existing_server_default=sa.text("nextval('cluster_id_seq'::regclass)"),
    )
    op.drop_constraint("operation_cluster_id_fkey", "operation", type_="foreignkey")
    op.create_foreign_key(None, "operation", "cluster", ["cluster_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation", "cluster_repository")
    op.alter_column("operation", "cluster_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint(None, "operation", type_="foreignkey")
    op.create_foreign_key("operation_cluster_id_fkey", "operation", "cluster", ["cluster_id"], ["id"])
    op.alter_column(
        "cluster",
        "id",
        existing_type=sa.INTEGER(),
        existing_server_default=sa.text("nextval('cluster_id_seq'::regclass)"),
    )
    # ### end Alembic commands ###
