"""Add cluster status field

Revision ID: 6915ba4b822f
Revises: 32027a8dbaec
Create Date: 2023-08-18 09:48:03.654955

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "6915ba4b822f"
down_revision = "32027a8dbaec"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cluster",
        sa.Column(
            "status",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="running",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cluster", "status")
    # ### end Alembic commands ###
