"""Add status field

Revision ID: 5bad183d950f
Revises: e3db0ecbe039
Create Date: 2023-09-05 16:41:14.897137

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5bad183d950f"
down_revision = "e3db0ecbe039"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cluster",
        "status",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_server_default=sa.text("'running'::character varying"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cluster",
        "status",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_server_default=sa.text("'running'::character varying"),
    )
    # ### end Alembic commands ###
