"""Add vpc_endpoint_service_name field

Revision ID: a535e0608665
Revises: 92e3864c4871
Create Date: 2023-04-11 14:27:40.236085

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "a535e0608665"
down_revision = "92e3864c4871"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cluster",
        sa.Column(
            "vpc_endpoint_service_name",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cluster", "vpc_endpoint_service_name")
    # ### end Alembic commands ###
