"""Create clientnamespace table

Revision ID: 3fe9f3ae2fb6
Revises: 5bad183d950f
Create Date: 2023-09-21 10:33:54.224275

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "3fe9f3ae2fb6"
down_revision = "5bad183d950f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clientnamespace",
        sa.Column("admin", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("viewer", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("editor", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("cluster_id", sa.Integer(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["cluster.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("clientnamespace")
    # ### end Alembic commands ###
