"""Add network cidr field

Revision ID: 92e3864c4871
Revises: a29700d9a5ab
Create Date: 2023-04-04 16:53:15.609282

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "92e3864c4871"
down_revision = "a29700d9a5ab"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cluster",
        sa.Column(
            "network_cidr",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="0.0.0.0/0",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cluster", "network_cidr")
    # ### end Alembic commands ###
