"""Add cmdb_app_id field to clusters

Revision ID: 32027a8dbaec
Revises: ea37d341baed
Create Date: 2023-06-30 12:37:31.071270

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "32027a8dbaec"
down_revision = "ea37d341baed"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cluster",
        sa.Column("cmdb_app_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cluster", "cmdb_app_id")
    # ### end Alembic commands ###
