"""Add cmdb appd id field

Revision ID: a29700d9a5ab
Revises: a90bf054665a
Create Date: 2023-03-01 16:34:48.428332

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "a29700d9a5ab"
down_revision = "a90bf054665a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cluster",
        sa.Column("cmdb_appd_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cluster", "cmdb_appd_id")
    # ### end Alembic commands ###
