"""Add account_name field

Revision ID: 5d5e9ad536ee
Revises: 3fe9f3ae2fb6
Create Date: 2023-10-12 09:25:31.559969

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "5d5e9ad536ee"
down_revision = "3fe9f3ae2fb6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cluster",
        sa.Column(
            "account_name",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cluster", "account_name")
    # ### end Alembic commands ###
