"""Add feature constraints

Revision ID: d2f5b74e6a8f
Revises: 3c41d177d800
Create Date: 2024-11-26 16:01:04.685686

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d2f5b74e6a8f"
down_revision = "3c41d177d800"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "feature",
        sa.Column("constraints", sa.JSON(), server_default="[]", nullable=True),
    )
    op.drop_constraint("feature_name_type_uc", "feature", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("feature_name_type_uc", "feature", ["name", "type"])
    op.drop_column("feature", "constraints")
    # ### end Alembic commands ###
