"""Add multi_tenant field

Revision ID: f1e574399590
Revises: 492c294ca425
Create Date: 2024-07-08 13:04:34.230119

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f1e574399590"
down_revision = "492c294ca425"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # https://stackoverflow.com/questions/12045698/sqlalchemy-boolean-value-is-none#comment69750602_12045897
    op.add_column(
        "cluster",
        sa.Column("multi_tenant", sa.Boolean(), server_default="f", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cluster", "multi_tenant")
    # ### end Alembic commands ###
