"""Create User-features table

Revision ID: 7f4ae9be9f6a
Revises: 4a27ed2c0828
Create Date: 2024-09-17 14:43:23.094770

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "7f4ae9be9f6a"
down_revision = "4a27ed2c0828"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userfeature",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("namespace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("repo_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("commit_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("helm_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("values_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["cluster.id"],
        ),
        sa.PrimaryKeyConstraint("name", "cluster_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("userfeature")
    # ### end Alembic commands ###
