"""Add additional node pool

Revision ID: 4a27ed2c0828
Revises: bfb992ebe994
Create Date: 2024-09-26 14:57:17.943942

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "4a27ed2c0828"
down_revision = "bfb992ebe994"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "additionalnodepool",
        sa.Column("cluster_id", sa.Integer(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("node_min_count", sa.Integer(), nullable=False),
        sa.Column("node_max_count", sa.Integer(), nullable=False),
        sa.Column("tshirt_size", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["cluster.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("additionalnodepool")
    # ### end Alembic commands ###
