"""Add sku tier field

Revision ID: 9080eef9ab03
Revises: aae7fbcb9e15
Create Date: 2024-02-14 17:04:35.044213

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "9080eef9ab03"
down_revision = "aae7fbcb9e15"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cluster",
        sa.Column("azure_sku_tier", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cluster", "azure_sku_tier")
    # ### end Alembic commands ###
