"""Add aws_remote_account_ids field

Revision ID: bfb992ebe994
Revises: f1e574399590
Create Date: 2024-07-10 14:05:49.315281

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bfb992ebe994"
down_revision = "f1e574399590"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cluster", sa.Column("aws_remote_account_ids", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cluster", "aws_remote_account_ids")
    # ### end Alembic commands ###
