"""cleanup jenkins references

Revision ID: eb900294dc4b
Revises: 7f4ae9be9f6a
Create Date: 2024-10-10 13:28:27.780238

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "eb900294dc4b"
down_revision = "7f4ae9be9f6a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name="operation", column_name="jenkins_url", new_column_name="cicd_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name="operation", column_name="cicd_url", new_column_name="jenkins_url")
    # ### end Alembic commands ###
