"""Add Kube-Downscaler period parameters

Revision ID: 3c41d177d800
Revises: eb900294dc4b
Create Date: 2024-10-17 10:22:28.589890

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "3c41d177d800"
down_revision = "eb900294dc4b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cluster", sa.Column("kubedownscaler_downscale_period", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "cluster", sa.Column("kubedownscaler_upscale_period", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cluster", "kubedownscaler_upscale_period")
    op.drop_column("cluster", "kubedownscaler_downscale_period")
    # ### end Alembic commands ###
