"""Add cluster oidc issuer url

Revision ID: aae7fbcb9e15
Revises: dddf9fbea89e
Create Date: 2024-01-10 12:01:10.971128

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "aae7fbcb9e15"
down_revision = "dddf9fbea89e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cluster",
        sa.Column("cluster_oidc_issuer_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cluster", "cluster_oidc_issuer_url")
    # ### end Alembic commands ###
