"""Migrate missing fields

Revision ID: 492c294ca425
Revises: 9080eef9ab03
Create Date: 2024-03-14 11:34:21.022157

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "492c294ca425"
down_revision = "9080eef9ab03"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cluster", sa.Column("authorized_api_ip_ranges", sa.JSON(), nullable=True))
    op.add_column(
        "cluster",
        sa.Column("aws_vpc_endpoint_remote_account_ids", sa.JSON(), nullable=True),
    )
    op.add_column(
        "cluster",
        sa.Column("appd_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "cluster",
        sa.Column("dns_zone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "cluster",
        sa.Column(
            "logging_retention_period",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    op.add_column(
        "cluster",
        sa.Column(
            "tracing_retention_period",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    op.add_column(
        "cluster",
        sa.Column("pod_cidr", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "cluster",
        sa.Column("service_cidr", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "cluster",
        sa.Column("dns_service_ip", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "cluster",
        sa.Column("aws_vpc", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "cluster",
        sa.Column("azure_subnet_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "cluster",
        sa.Column("azure_vnet_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "cluster",
        sa.Column(
            "azure_vnet_resource_group",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cluster", "azure_vnet_resource_group")
    op.drop_column("cluster", "azure_vnet_name")
    op.drop_column("cluster", "azure_subnet_name")
    op.drop_column("cluster", "aws_vpc")
    op.drop_column("cluster", "dns_service_ip")
    op.drop_column("cluster", "service_cidr")
    op.drop_column("cluster", "pod_cidr")
    op.drop_column("cluster", "tracing_retention_period")
    op.drop_column("cluster", "logging_retention_period")
    op.drop_column("cluster", "dns_zone")
    op.drop_column("cluster", "appd_id")
    op.drop_column("cluster", "aws_vpc_endpoint_remote_account_ids")
    op.drop_column("cluster", "authorized_api_ip_ranges")
    # ### end Alembic commands ###
