"""Adding 'created_at' and 'updated_at' columns to 'cluster' table

Revision ID: 37f752684c65
Revises: db119f72f5d3
Create Date: 2025-06-04 17:17:47.555336

"""

import sqlalchemy as sa
from alembic import op
from migrations.triggers import create_trigger

# revision identifiers, used by Alembic.
revision = "37f752684c65"
down_revision = "db119f72f5d3"
branch_labels = None
depends_on = None

trigger = create_trigger("cluster")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cluster", sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False)
    )
    op.add_column("cluster", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

    op.create_entity(trigger)


def downgrade() -> None:
    op.drop_entity(trigger)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cluster", "updated_at")
    op.drop_column("cluster", "created_at")
    # ### end Alembic commands ###
