"""add azure managed identity object ids

Revision ID: 7df528a88220
Revises: 37f752684c65
Create Date: 2025-09-01 15:46:37.668784

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "7df528a88220"
down_revision = "37f752684c65"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cluster", sa.Column("mi_agentpool_object_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("cluster", sa.Column("mi_cluster_object_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cluster", "mi_cluster_object_id")
    op.drop_column("cluster", "mi_agentpool_object_id")
    # ### end Alembic commands ###
