"""add reserved_namespaces to release table

Revision ID: 90e10d167091
Revises: 7df528a88220
Create Date: 2025-09-10 13:17:11.971738

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "90e10d167091"
down_revision = "7df528a88220"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("release", sa.Column("reserved_namespaces", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("release", "reserved_namespaces")
    # ### end Alembic commands ###
