"""Adding trigger function to use on updated_at columns

Revision ID: db119f72f5d3
Revises: bde7104a1c48
Create Date: 2025-06-04 17:16:09.653108

"""

from alembic import op
from migrations.triggers import set_updated_at_trigger_function

# revision identifiers, used by Alembic.
revision = "db119f72f5d3"
down_revision = "bde7104a1c48"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_entity(set_updated_at_trigger_function)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_entity(set_updated_at_trigger_function)
    # ### end Alembic commands ###
