"""add domain allowlist column

Revision ID: 0f3a5437c506
Revises: b6d9e122465f
Create Date: 2025-03-05 13:57:00.823236

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0f3a5437c506"
down_revision = "b6d9e122465f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cluster", sa.Column("domain_allowlist", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cluster", "domain_allowlist")
    # ### end Alembic commands ###
