"""Add client_otlp_endpoint info

Revision ID: bde7104a1c48
Revises: c7789ff947e0
Create Date: 2025-05-15 15:01:17.105139

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "bde7104a1c48"
down_revision = "c7789ff947e0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clientotlpendpoint",
        sa.Column("signals", sa.JSON(), nullable=True),
        sa.Column("auth", sa.JSON(), nullable=True),
        sa.Column("cluster_id", sa.Integer(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("endpoint", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["cluster.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("clientotlpendpoint")
    # ### end Alembic commands ###
