"""add namespaced features support

Revision ID: e4979347996f
Revises: 90e10d167091
Create Date: 2025-09-23 18:05:30.414140

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e4979347996f"
down_revision = "90e10d167091"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clusterfeature", sa.Column("config", sa.JSON(), nullable=True))
    op.add_column("feature", sa.Column("namespaced", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("feature", "namespaced")
    op.drop_column("clusterfeature", "config")
    # ### end Alembic commands ###
