"""Add gateway_api_enabled column

Revision ID: b6d9e122465f
Revises: d2f5b74e6a8f
Create Date: 2025-01-31 10:19:57.271259

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b6d9e122465f"
down_revision = "d2f5b74e6a8f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cluster", sa.Column("gateway_api_enabled", sa.Boolean(), server_default="f", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cluster", "gateway_api_enabled")
    # ### end Alembic commands ###
