"""Add 'uptime_period' column to Cluster table

Revision ID: 54b46bacd8ec
Revises: fc3836a557f6
Create Date: 2026-04-16 12:29:10.793805

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "54b46bacd8ec"
down_revision = "fc3836a557f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cluster", sa.Column("uptime_period", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cluster", "uptime_period")
    # ### end Alembic commands ###
