"""Add vpc_endpoint_service_ingress_name

Revision ID: f3d01f08893a
Revises: 5ba2302a5f7d
Create Date: 2026-03-24 17:41:21.887447

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "f3d01f08893a"
down_revision = "5ba2302a5f7d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cluster", sa.Column("vpc_endpoint_service_ingress_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cluster", "vpc_endpoint_service_ingress_name")
    # ### end Alembic commands ###
