"""Add config field to Client OTLP table

Revision ID: 5ba2302a5f7d
Revises: e4612c8a30d1
Create Date: 2026-03-18 12:08:01.383523

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5ba2302a5f7d"
down_revision = "e4612c8a30d1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clientotlpendpoint", sa.Column("config", sa.JSON(), nullable=True))
    # ### end Alembic commands ###

    op.alter_column(
        "clientotlpendpoint",
        "auth",
        existing_type=sa.JSON(),
        nullable=True,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clientotlpendpoint", "config")
    # ### end Alembic commands ###

    op.alter_column(
        "clientotlpendpoint",
        "auth",
        existing_type=sa.JSON(),
        nullable=False,
    )
