"""Backfill 'uptime_period' column

Revision ID: b06516d16522
Revises: 54b46bacd8ec
Create Date: 2026-04-29 14:08:41.684733

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "b06516d16522"
down_revision = "54b46bacd8ec"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    """For clarity, this migration is reverse-engineering the
    'kubedownscaler_downscale_period' and 'kubedownscaler_upscale_period' fields to
    produce a value for 'uptime_period'.

    Essentially, the end of the upscale period is the start of the uptime period,
    and the start of the downscale period is the end of the uptime period.

    For example:
    kubedownscaler_downscale_period -> Mon-Fri 18:00-18:15 Europe/Berlin
    kubedownscaler_upscale_period -> Mon-Fri 07:15-07:30 Europe/Berlin
    results in Mon-Fri 07:30-18:00 Europe/Berlin, which will be the 'uptime_period'.

    To understand how "split_part" works check: https://www.postgresql.org/docs/9.1/functions-string.html
    """

    op.execute(
        """
        UPDATE cluster
        SET uptime_period = CONCAT(
            split_part(kubedownscaler_upscale_period, ' ', 1),
            ' ',
            split_part(split_part(kubedownscaler_upscale_period, ' ', 2), '-', 2),
            '-',
            split_part(split_part(kubedownscaler_downscale_period, ' ', 2), '-', 1),
            ' ',
            split_part(kubedownscaler_upscale_period, ' ', 3)
        )
        WHERE kubedownscaler_upscale_period IS NOT NULL
            AND kubedownscaler_downscale_period IS NOT NULL
            AND uptime_period IS NULL
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE cluster
        SET uptime_period = NULL
        WHERE kubedownscaler_upscale_period IS NOT NULL
          AND kubedownscaler_downscale_period IS NOT NULL
        """
    )
    # ### end Alembic commands ###
