"""Adjusting DB structure against ORM changes

Revision ID: fc3836a557f6
Revises: f3d01f08893a
Create Date: 2026-04-02 14:59:23.365716

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fc3836a557f6"
down_revision = "f3d01f08893a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_additionalnodepool_cluster_id"), "additionalnodepool", ["cluster_id"], unique=False)
    op.create_index(op.f("ix_clientnamespace_cluster_id"), "clientnamespace", ["cluster_id"], unique=False)
    op.alter_column(
        "clientotlpendpoint", "signals", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=False
    )
    op.create_index(op.f("ix_clientotlpendpoint_cluster_id"), "clientotlpendpoint", ["cluster_id"], unique=False)
    op.create_index(op.f("ix_operation_cluster_id"), "operation", ["cluster_id"], unique=False)
    op.create_index(op.f("ix_storageclass_cluster_id"), "storageclass", ["cluster_id"], unique=False)
    op.create_index(op.f("ix_teamswebhook_cluster_id"), "teamswebhook", ["cluster_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_teamswebhook_cluster_id"), table_name="teamswebhook")
    op.drop_index(op.f("ix_storageclass_cluster_id"), table_name="storageclass")
    op.drop_index(op.f("ix_operation_cluster_id"), table_name="operation")
    op.drop_index(op.f("ix_clientotlpendpoint_cluster_id"), table_name="clientotlpendpoint")
    op.alter_column(
        "clientotlpendpoint", "signals", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=True
    )
    op.drop_index(op.f("ix_clientnamespace_cluster_id"), table_name="clientnamespace")
    op.drop_index(op.f("ix_additionalnodepool_cluster_id"), table_name="additionalnodepool")
    # ### end Alembic commands ###
