"""add headlamp enabled to cluster

Revision ID: 44775c618d1f
Revises: b06516d16522
Create Date: 2026-05-07 09:58:22.507553

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "44775c618d1f"
down_revision = "b06516d16522"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cluster", sa.Column("headlamp_enabled", sa.Boolean(), server_default="f", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cluster", "headlamp_enabled")
    # ### end Alembic commands ###
